logging:
    level: warn

#spring:
#    datasource:
#      url: jdbc:mysql://rm-uf69tmdc5ym311144o.mysql.rds.aliyuncs.com/rex?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
#      username: superzoc
#      password: Zc09110817
#logger-db:
#    datasource:
#      url: jdbc:mysql://rm-uf69tmdc5ym311144o.mysql.rds.aliyuncs.com/rex_log?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
#      username: superzoc
#      password: Zc09110817
spring:
    datasource:
      url: jdbc:mysql://178.25.1.48/rex?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
      username: root
      password: cdjgj.=mysql1
logger-db:
    datasource:
      url: jdbc:mysql://178.25.1.48/rex_log?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
      username: root
      password: cdjgj.=mysql1
hsweb:
    web:
      upload:
          static-location: /upload/
    app:
      name: 蓉E行交通众治平台-icbc
com:
  zmcsoft:
    pay:
      icbc:
          callback: http://cdjjjt.rex.cdjg.gov.cn:8090/pay/icbc/callback
      unionpay:
          callback: http://cdjjjt.rex.cdjg.gov.cn:8090/pay/unionpay/callback
    logger:
        data-source-id: loggerDb
    icbc:
      ftp:
        username: cdjj
        password: cdjj-Pass321
        host: 95.2.2.45
        port: 21
        max-active: 100
        initial-size: 2
        min-idle: 5
        max-wait: 50000
        min-evictable-idle-time-millis: 300000
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        time-between-eviction-runs-millis: 60000
        max-open-prepared-statements: 2000
icbc:
  socket:
    host: 95.2.2.43
    port: 10016
redission:
    host: redis://178.25.1.41:6380